include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/generated/**"
    - "lib/core/api/generated/**"
    - "lib/core/db/**.g.dart"

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    one_member_abstracts: false
    avoid_classes_with_only_static_members: false
    sort_constructors_first: false
    flutter_style_todos: false
